server:
  port: 80

spring:
  application:
    name: domain-hunter

  threads:
    virtual:
      enabled: true

  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/domain_hunter?Unicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:1}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:domain-hunter}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  level:
    root: info
    web: info
    sql: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  group-configs:
    - group: default
      paths-to-match: /api/**

knife4j:
  enable: true
  documents:
    - group: default
      name: README
      locations: classpath:static/doc/*

app:
  check-api: https://checkapi.aliyun.com/check/domaincheck
