server:
  port: 8080

spring:
  application:
    name: domain-hunter

  threads:
    virtual:
      enabled: true

  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/domain_hunter?Unicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    web: info
    sql: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  group-configs:
    - group: default
      paths-to-match: /api/**

knife4j:
  enable: true
  documents:
    - group: default
      name: README
      locations: classpath:static/doc/*

app:
  check-api: https://checkapi.aliyun.com/check/domaincheck
